spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    jpa:
      show-sql: true
      open-in-view: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          globally_quoted_identifiers: true
          jdbc:
            time_zone: Asia/Shanghai


  transaction:
    rollback-on-commit-failure: true


server:
  port: 9988
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
